x-args-defaults:
  &args-defaults
  UID: 1000
  GID: 1000
  TAG: base
  NUM_THREADS: 8
  DISTRO: humble
  http_proxy: ""
  https_proxy: ""

x-build-defaults:
 &build-defaults
  context: .
  dockerfile: Dockerfile
  # additional_contexts:
  #   src_ctx: ../workspace
  args:
    <<: *args-defaults

services:
  rtabmap:
    image: humble/rtabmap_ros:base
    build:
      <<: *build-defaults
      args:
        <<: *args-defaults
        CONTAINER_NAME: rtabmap_ros
      target: rtabmap-ros-release
  slam_toolbox:
    image: humble/slam_toolbox:base
    build:
      <<: *build-defaults
      args:
        <<: *args-defaults
        CONTAINER_NAME: slam_toolbox
      target: slam-toolbox-release
